### ISSUE TITLE
plugin's entry_points.txt is lost with poetry packaging

### ISSUE THREAD

**Issue by Kreisfahrer** [astraw38/pytest-assume#24]
Version tested 1.2.2

Was working before release of 2.1:
![image](https://user-images.githubusercontent.com/5236540/61525820-dbd01280-aa21-11e9-8429-ac70ac6ae218.png)
![image](https://user-images.githubusercontent.com/5236540/61525919-0b7f1a80-aa22-11e9-9cee-22a03f021f35.png)
As you can see wheel generated by bdist_wheel contains needed entry_points.txt

After release of 2.1 same 1.2.2 version:
![image](https://user-images.githubusercontent.com/5236540/61526046-526d1000-aa22-11e9-8f6c-d74832b68061.png)
![image](https://user-images.githubusercontent.com/5236540/61526057-5a2cb480-aa22-11e9-87c6-fe59f2e1d106.png)
As you can see wheel generated by poetry DOES NOT contain needed entry_points.txt

**Comment by astraw38** [comment]
How are you generating the wheel via poetry?

**Comment by Kreisfahrer** [comment]
I got it from PYPI

**Comment by astraw38** [comment]
If I grab the wheel directly from [pypi](https://files.pythonhosted.org/packages/09/6f/1b34488dcffe5870007213a1d2c4b92ac452379b74c9fd194f6d83990ca1/pytest_assume-2.1.0-py3-none-any.whl) and unpack it w/ ``wheel unpack pytest_assume-2.1.0-py3-none-any.whl``, I still see the entry_points.txt. 

That's why I'm wondering where poetry comes in here -- just an install or a build? I had done some testing w/ poetry a while back, but never got around to pushing a .toml file. Now I don't mind pushing that .toml now, but I'm curious as to how you got poetry to generate that wheel (since it shows as the generator), since it won't generate one for me unless I have a .toml file.

**Comment by Kreisfahrer** [comment]
please take 1.2.2 version

**Comment by astraw38** [comment]
Ah, I see what you mean. I thought when you meant that it stopped working after release of 2.1, you meant the release of 2.1 wasn't working. There's 2 whls that are in pypi, one which works, one that doesn't. That's likely from my testing w/ poetry a while back -_-. 

Should be fixed now (deleted the extraneous wheel)

**Comment by Kreisfahrer** [comment]
I can see that 2.1.0 version is built with bdist-wheel and does contain entry_points.txt. However, version 1.2.2 is

**Comment by Kreisfahrer** [comment]
Yes, it is fixed now! Thanks! Testing on pypi probably is not a good idea though. :)

**Comment by astraw38** [comment]
Quite! I neglected to clear my dist/ folder before pushing the latest build. Happened to have the old build in there.
